# NumpyVsPythonList

In [3]:
l=range(1000000)
#(%time), tells you the time require to complete the process
%time for i in range(1,10): result=[x*2 for x in l]

Wall time: 1.26 s


In [2]:
import numpy as np

arr = np.arange(1000000)

%time for i in range(1,10): result2=arr*2 #the time required is comparitively less than python list
#numpy is almost 100 times faster than python list calculation

Wall time: 48 ms


# A Multidimensional Array Object

In [5]:
zero_element_array=np.zeros((4,4))
#an array is created with all the element is zero,on the tuple you initialize the size of that array
zero_element_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
Ones_element_array=np.ones((5,5))
#an array is created with all the element is one, on the tuple again you initialize the size of that array
Ones_element_array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [3]:
Empty_element_array=np.empty((5,5))
#an array is created with all the element is random, on the tuple again you initialize the size of that array
Empty_element_array

#empty function randomly generate any sort of value

array([[6.23042070e-307, 0.00000000e+000, 1.72451033e-307,
        1.44635488e-307, 1.37962320e-306],
       [1.29060871e-306, 7.56603881e-307, 7.56599807e-307,
        8.90104239e-307, 1.24610383e-306],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 1.29062229e-306],
       [1.29060531e-306, 6.89805151e-307, 7.56592338e-307,
        6.89807188e-307, 1.37961302e-306],
       [8.45559303e-307, 1.06811422e-306, 1.05694828e-307,
        2.22522596e-306, 2.18568966e-312]])

In [10]:
#you can convert the list of the simple python with the array of numpy by using np.array
List=[1,3,5,7,9]

L=np.array(List)
L

array([1, 3, 5, 7, 9])

In [6]:
#np.arange(starting point, ending point, step size) create an numpy array with some specific range you give

One_D_array=np.arange(1,100,10)
One_D_array

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [7]:
Second_One_D_array=np.arange(1,100)   #arange don't generate the random values
Second_One_D_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [8]:
Third_One_D_array=np.arange(1,100,20)   #arange don't generate the random values
Third_One_D_array

array([ 1, 21, 41, 61, 81])

In [11]:
#you can also check the shape of the array by using element_name.shape like,

One_D_array_shape = One_D_array.shape
Second_One_D_array_shape = Second_One_D_array.shape  #remember, no parenthesis
Third_One_D_array_shape = Third_One_D_array.shape

print(One_D_array_shape)   #shape tells that how many element are in the array of the numpy
print(Second_One_D_array_shape)  #like the size of an numpy
print(Third_One_D_array_shape)

(10,)
(99,)
(5,)


In [12]:
w=np.zeros((10,10))
#reshape can convert the original shape of the array to the desire shape you want
s=w.reshape((2,2,5,5))   #size given by tuples

print(s)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [13]:
#you can also see the datatype of an array by using element_name.dtype like,
print("data type of the numpy array s is :{}".format(s.dtype))
#you can also see the dimentions of an array by element_name.ndim
print("Dimention of the numpy array s is :{}".format(s.ndim))

data type of the numpy array s is :float64
Dimention of the numpy array s is :4


# Arithmetic with ndarray

In [35]:
#you can perform multiple operation on two numpy array directly by +,-,x and / sign as you add two values
Numpy_array=np.array([[1., 2., 3.], [4., 5., 6.]])
#we always passes list on .array method
add_array=Numpy_array + Numpy_array
print(add_array)

subs_array=Numpy_array - Numpy_array
print(subs_array)

mul_array=Numpy_array * Numpy_array
print(mul_array)

div_array=Numpy_array / Numpy_array
print(div_array)

half_power_array=Numpy_array ** 0.5
print(half_power_array)

#you can also compare two values on an array and return true/false as an output
Numpy_array_two=np.array([[1., 4., 6.], [4., 7., 6.]])
boolean_array= Numpy_array < Numpy_array_two
print(boolean_array)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[[False  True  True]
 [False  True False]]


In [15]:
#you can also generate random array by using np.random.randn() 

random_array_a=np.random.randn((10))
print("First random Array: {}".format(random_array_a))

random_array_b=np.random.randn((10))
print("Second random Array: {}".format(random_array_b))

First random Array: [ 0.20584828  1.8220079   1.00807402  1.25536243  0.35631901  0.52313592
 -0.52163182 -0.59501447  0.35826543  0.52381085]
Second random Array: [-0.77137475 -1.94688617  1.15862137  0.43764039  1.33625967  0.20017834
 -0.65386809 -0.87418548  0.70757048  0.69182945]


In [16]:
print("Addition of two Random Arrays: {}".format(random_array_a + random_array_b))
print("Substraction of two Random Arrays: {}".format(random_array_a - random_array_b))
print("Multiplication of two Random Arrays: {}".format(random_array_a * random_array_b))
print("Division of two Random Arrays: {}".format(random_array_a / random_array_b))

Addition of two Random Arrays: [-0.56552647 -0.12487827  2.16669539  1.69300282  1.69257869  0.72331426
 -1.17549991 -1.46919995  1.06583592  1.2156403 ]
Substraction of two Random Arrays: [ 0.97722303  3.76889407 -0.15054735  0.81772204 -0.97994066  0.32295758
  0.13223627  0.27917101 -0.34930505 -0.1680186 ]
Multiplication of two Random Arrays: [-0.15878617 -3.54724199  1.1679761   0.5493973   0.47613473  0.10472048
  0.3410784   0.52015301  0.25349805  0.36238777]
Division of two Random Arrays: [-0.26685898 -0.93585744  0.87006337  2.86847938  0.26665402  2.61334932
  0.79776308  0.68065014  0.5063318   0.7571387 ]


In [17]:
print("Random array with true/false statement: {}".format(random_array_a>0))
print(random_array_a[random_array_a>0]) #gives those element which is true

Random array with true/false statement: [ True  True  True  True  True  True False False  True  True]
[0.20584828 1.8220079  1.00807402 1.25536243 0.35631901 0.52313592
 0.35826543 0.52381085]


# Indexing & Slicing

In [21]:
#some example about indexing relate with numpy

import numpy as np
x = np.array([2,3,4,6,7,8])
print(x[2])

#boolean indexing
print(x[x>=6])   #index where the condition is also working

#Fancy Indexing
print(x[[2,4]]) #indexing passing by list and select that number against index

#Another Example,
y = np.array([3,5,6,8,9,11,13])  #gives those values which on your given position
print(y[[1,3]])

4
[6 7 8]
[4 7]
[5 8]


In [23]:
#some example about Silicing relate with numpy

x=np.random.randn(5, 5)
print(x)

print("\n")
print("Whole First Row: {}".format(x[0]))
print("\n")
print("2nd row 4th Column: {}".format(x[1][3])) #if you select single value to be as a output than it must be a large value

print("\n")

print("Even rows with all columns of that rows:\n {}".format(x[0:5:2,::]))  #for Even number list


[[ 0.10658069  0.83850311  0.19514427 -1.12500041 -0.16947016]
 [ 1.35826752  0.56330292 -0.03638047  0.55584402  1.93299963]
 [-0.11151012  0.25054554 -1.50938278 -1.53281007  0.67189399]
 [ 0.18579619  1.41320552  1.95396361 -1.49636837 -0.57181486]
 [-0.38755107 -0.56506238  1.16152038 -0.61228023  0.00463909]]


Whole First Row: [ 0.10658069  0.83850311  0.19514427 -1.12500041 -0.16947016]


2nd row 4th Column: 0.5558440187238955


Even rows with all columns of that rows:
 [[ 0.10658069  0.83850311  0.19514427 -1.12500041 -0.16947016]
 [-0.11151012  0.25054554 -1.50938278 -1.53281007  0.67189399]
 [-0.38755107 -0.56506238  1.16152038 -0.61228023  0.00463909]]


In [26]:
#if you want all rows and required columns than,
print("all rows and required columns:\n {}".format(x[::,0:5:2]))
#[{starting:ending}:gap for rows, {starting:ending}:gap for columns]

all rows and required columns:
 [[ 0.38255328 -0.10202216 -1.33865867]
 [-0.31935107 -0.16245125  0.99222302]
 [ 2.13699246  0.01773349  1.17725478]
 [-1.8857378   0.44652668  0.47251758]
 [-0.40207246  0.23311799  0.78798257]]


In [24]:
w=np.ones([5, 5])
print("5th Dimentional Array with all Ones:\n {}".format(w))

w[1:-1,1:-1]=0  #gives range that left starting row & column and ending row & column.
print("\n")
print("5th Dimentional Array with Zeroes at the centre:\n {}".format(w))

5th Dimentional Array with all Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


5th Dimentional Array with Zeroes at the centre:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Fast element-wise array functions

In [43]:
s=np.array([1,4,9,16,25,36])
print("Square root of s Array:{}".format(np.sqrt(s)))
print("Square Power of s Array:{}".format(np.power(s, 2)))
print("Cubic Power of s Array:{}".format(np.power(s, 3)))
print("\n")

e=[2,5,7,5,8,3]
print("Mazimum Values from the two arrays: {}".format(np.maximum(s, e)))
#np.maximum traverse every value from the both arrray and gives the largest value of any particular position in the both array
#and take those two arrays to form one array


Square root of s Array:[1. 2. 3. 4. 5. 6.]
Square Power of s Array:[   1   16   81  256  625 1296]
Cubic Power of s Array:[    1    64   729  4096 15625 46656]


Mazimum Values from the two arrays: [ 2  5  9 16 25 36]


# Np.where

In [25]:
# Ternary operator takes three operand as an input (if condition is satisfy than on first operand on which you put condition is
# is running  and if other condition is satisfy than the second operand is running)

# np.where(condition, option A, option B)
#condition: the condition
#Option A: what is to do with entries for which the condition is true
#Option B: what to do with entries for which the condition is false
# np.where is apply on whole array
# where funtion is uses where on, when we're working as a data scientist and we get same empty or null values in the array than
# fill those spaces using np.where()
# you can also filtered out the values from an array using np.where

import numpy as np

salary=np.array([0, -1, 100000, 50000])# these are the salary set of any particular faculty
#0 and -1 represent that the 1st and 2nd employee don't want to show their salaries
print("Salaries of all Employee(lum sum):")
print(np.where(salary<=0, 35000, salary))
print("\n")
print("Salaries Private(means don't be overwrite):")
print(np.where(salary<=0, "Salary hide", salary))

Salaries of all Employee(lum sum):
[ 35000  35000 100000  50000]


Salaries Private(means don't be overwrite):
['Salary hide' 'Salary hide' '100000' '50000']


# Mathematical & Statistical Methods

In [26]:
import numpy as np

# mean(): returns the mean value computed over the array
# cumsum(): returns the cumulative sum of array elements
# cumprod(): returns the cumulative product of array elements

#some methods which work on boolean arrays
# sum(): counting true values in a boolean array
# any(): tests wether one or more values in an array is true
# all(): checks if every value is true return true, otherwise return false

#in numpy, we also have some sorting, unique methods
# np.sort()
# np.unique()

print("Some Mathematical & Statiaticals Methods while using Numpy:")
print("\n")
Array=np.array([12,32,54,65,45,55])
print("1) The mean of the given Array: '{}'".format(Array.mean()))
print("2) The Cumulative Summation of an Array: {}".format(Array.cumsum()))
print("3) The Cumulative Product of an Array: {}".format(Array.cumprod()))
print("\n")
Array_comparisn = Array>40   #in this line, all values of an Array compare by 40 and return answer in boolean(true/false)
print(Array_comparisn)
print("The Total No of true in an Array: {}".format(Array_comparisn.sum()))  #gives sum of how many is true
print("Check, if any value is true(boolean Answer): {}".format(Array_comparisn.any()))
print("Check, if all value is true(boolean Answer): {}".format(Array_comparisn.all()))
print("\n")
another_array=np.array([5,2,7,3,1,9,8])
print("Array Before Sorting: {}".format(another_array))
another_array.sort()
print("Array After Sorting: {}".format(another_array))

#unique is not direct method like sort and it is call by,
second_array=np.array([2,2,4,5,6,7,7,8,9])
print("Given array is: {}".format(second_array))
print("Array after making unique set: {}".format(np.unique(second_array)))

Some Mathematical & Statiaticals Methods while using Numpy:


1) The mean of the given Array: '43.833333333333336'
2) The Cumulative Summation of an Array: [ 12  44  98 163 208 263]
3) The Cumulative Product of an Array: [        12        384      20736    1347840   60652800 -959063296]


[False False  True  True  True  True]
The Total No of true in an Array: 4
Check, if any value is true(boolean Answer): True
Check, if all value is true(boolean Answer): False


Array Before Sorting: [5 2 7 3 1 9 8]
Array After Sorting: [1 2 3 5 7 8 9]
Given array is: [2 2 4 5 6 7 7 8 9]
Array after making unique set: [2 4 5 6 7 8 9]


# File Input Output

In [7]:
import numpy as np

# you can completely save the array by using numpy lib
# np.save(filename.npy, array which you wanna save) if you don't give extention than numpy will automatically provides.
# np.load(filename.npy)
# np.savez(filename.npz, array1, array2)
    # when loading an .npz file, you get back a dictionary like object
    
x=[1,3,5,7,9,11]
y=[2,4,6,8,10,12]

np.save('testx', x)
loadx = np.load('testx.npy')
print(loadx)

[ 1  3  5  7  9 11]


In [16]:
np.savez('testxy', x=x, y=y)
loadxy = np.load('testxy.npz')   #save array as a dictionary
print(loadxy)

In [19]:
#you can retrieve it by,
print("Values of x from the two arrays: {}".format(loadxy['x']))
print("Values of y from the two arrays: {}".format(loadxy['y']))

Values of x from the two arrays: [ 1  3  5  7  9 11]
Values of y from the two arrays: [ 2  4  6  8 10 12]


# Linear Algebra Functions

In [34]:
#through numpy, you can vectorized support for your code and take homogenous data for use
#we can also get some numerical computing facilities through numpy
#you can find out the dot product, diagonal matrix, inverse of the matrix, igone values from the matrix

w = np.random.randn(3, 3)
a = np.random.randn(3, 3)
print("Matrix W and Matrix A:")
print(w,"\n\n",a)
print("\n")
print("1) Dot product of w and a:\n {}".format(w.dot(a)))
print("2) Transpose of w:\n {}".format(w.transpose()))
print("3) Trace of w:\n {}".format(w.trace()))
print("4a) Diagonal of Matrix w:\n {}".format(np.diag(w)))
print("4b) Diagonal of Matrix a:\n {}".format(np.diag(a)))

Matrix W and Matrix A:
[[ 0.30115687 -0.05332603 -0.82505819]
 [-0.16360176  1.29021279 -0.99880239]
 [-0.13115589 -0.37259053  1.64717747]] 

 [[-0.78507357 -1.72292522  0.07313599]
 [ 1.08326477 -0.75488857  0.97498684]
 [-2.30095562  0.92191337 -1.44519136]]


1) Dot product of w and a:
 [[ 1.60422578 -1.23924774  1.1624002 ]
 [ 3.82428145 -1.61290256  2.6894359 ]
 [-4.09072942  2.02579105 -2.75334972]]
2) Transpose of w:
 [[ 0.30115687 -0.16360176 -0.13115589]
 [-0.05332603  1.29021279 -0.37259053]
 [-0.82505819 -0.99880239  1.64717747]]
3) Trace of w:
 3.238547134665415
4a) Diagonal of Matrix w:
 [0.30115687 1.29021279 1.64717747]
4b) Diagonal of Matrix a:
 [-0.78507357 -0.75488857 -1.44519136]


In [35]:
#Generating diagonal Matrix
np.diag(np.diag(w))

array([[0.30115687, 0.        , 0.        ],
       [0.        , 1.29021279, 0.        ],
       [0.        , 0.        , 1.64717747]])

In [37]:
#upper and lower diagonal matrix

print("Diagonal of w:\n {}".format(np.diag(w, k=1)))  #upper diagonal
print("\n")
print("Diagonal of w:\n {}".format(np.diag(w, k=-1))) #lower diagonal

Diagonal of w:
 [-0.05332603 -0.99880239]


Diagonal of w:
 [-0.16360176 -0.37259053]


In [41]:
#inverse of the matrix

x = np.array([[1,2],[3,4]]) 
y = np.linalg.inv(x) 
print("Matrix:\n{}".format(x))
print("Inverse of the Matrix:\n{}".format(y))

Matrix:
[[1 2]
 [3 4]]
Inverse of the Matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]


# Pseudo Random Number

In [47]:
import numpy as np

#to remove biosness from our data, we use to make the data randomize
#it is impossible for computer to generate pure random numbers, because computer generate random numbers by some formula's
#computer generate random numbers by statistical distribution
#Pseudo Random Number generation:
# 1) Normal()
# 2) seed()
# 3) gamma()   generated one-D array
# 4) uniform()
    # but we must initialize the random number generator first, like we gives seed value to the generator

np.random.seed(5)  #use seed(), by which the numbers generated randomly remains same
print("Random Numbers Using Normal Generator:\n{}".format(np.random.normal(size=(3, 3))))
print("Random Numbers Using Uniform Generator:\n{}".format(np.random.uniform(size=(3,3))))

shape, scale = 2., 2.  # mean=4, std=2*sqrt(2)
print("Random Numbers Using Uniform Generator:\n{}".format(np.random.gamma(shape, scale, 10)))

Random Numbers Using Normal Generator:
[[ 0.44122749 -0.33087015  2.43077119]
 [-0.25209213  0.10960984  1.58248112]
 [-0.9092324  -0.59163666  0.18760323]]
Random Numbers Using Uniform Generator:
[[0.44130922 0.15830987 0.87993703]
 [0.27408646 0.41423502 0.29607993]
 [0.62878791 0.57983781 0.5999292 ]]
Random Numbers Using Uniform Generator:
[2.55209602 1.38837205 1.57431672 6.62482501 5.53190672 3.3418323
 3.06723474 5.82889589 1.95408949 3.31736372]


# NumPy Advanced Array Manipulations

# 1) Reshape

In [27]:
#you can reshape any number elements but the counting of elements remian same
#row major order and column major order are the main difference that how the data is store through the array
#C order (row order start to add values from rows) and fortran order (column order start to add values from column)
# you can specify that what kind of order you wanna reshape your array
# you can skip any dimention on your array while reshaping
# by using ravel()/flatten(), you can make any dimentional array to the one dimentional array

x=np.random.randn(4,5)   #(row, column)
print("Random Array Before Reshaping:\n\n{}".format(x))
print("Random Array After Reshaping:\n\n{}".format(x.reshape((2, 2, 5))))  #convert 2D Array into 3D Array
#compilar save this array in row major order by default,
#we can specify that we want column order by,
print("Random Array After Reshaping in Fortran Order:\n\n{}".format(x.reshape((2, 2, 5), order='F')))
#convert 2D Array into 3D Array

#you can skip any dimention of an array by using (-1) no-initialize value, and it is the responsibility of the numpy to deal 
#with this argument(to infer that what value this dimention must have)
print("Random Array After Reshaping with non-Initialize Value:\n\n{}".format(x.reshape((2, 2, -1))))
# but x is still two dimention because all the operations we done on x is obsolete, if we want operations to be done than we
# have to save these operations on another array type
# you can convert any dimentional array to one dimentional array by,
print("Convert 3D into 1D by Ravel Method:\n\n{}".format(x.ravel()))
print("Convert 3D into 1D by Flatten Method:\n\n{}".format(x.flatten()))
#these all are some basic contruct by which we can reshape an array

Random Array Before Reshaping:

[[ 0.91680513  0.74175323  0.33010691 -0.13691192 -0.29457377]
 [ 0.64109731 -0.24414084 -0.49152537 -0.31410362 -0.01064061]
 [ 0.70286902  1.94575128 -0.2921938  -0.55063575  0.63933693]
 [-0.34335051 -1.35358475  0.59081999 -0.96546315  1.02736526]]
Random Array After Reshaping:

[[[ 0.91680513  0.74175323  0.33010691 -0.13691192 -0.29457377]
  [ 0.64109731 -0.24414084 -0.49152537 -0.31410362 -0.01064061]]

 [[ 0.70286902  1.94575128 -0.2921938  -0.55063575  0.63933693]
  [-0.34335051 -1.35358475  0.59081999 -0.96546315  1.02736526]]]
Random Array After Reshaping in Fortran Order:

[[[ 0.91680513  0.74175323  0.33010691 -0.13691192 -0.29457377]
  [ 0.70286902  1.94575128 -0.2921938  -0.55063575  0.63933693]]

 [[ 0.64109731 -0.24414084 -0.49152537 -0.31410362 -0.01064061]
  [-0.34335051 -1.35358475  0.59081999 -0.96546315  1.02736526]]]
Random Array After Reshaping with non-Initialize Value:

[[[ 0.91680513  0.74175323  0.33010691 -0.13691192 -0.29457

# 2) Concatenate

In [30]:
#Concatenate: Takes a sequence(tuples, list, etc) of arrays and join them together in order along the input axis
#that argument(axis) tells you that if you want to concatenate row wise or column wise
#axis=0 is for concatenation of two arrays by row and axis=1 is for concatenation of two arrays by column
#Some Convenience functions of Concatenate
#vstack: stack array row wise(along axis=0) hstack: stack array row wise(along axis=1)

x=[[1,3,5], [7,9,11]]
array1=np.array(x)  #convert list into numpy's array
print("First converted Array:\n{}".format(array1))

y=[[2,4,6], [8,10,12]]
array2=np.array(y)  #convert list into numpy's array
print("Second converted Array:\n{}".format(array2))

First converted Array:
[[ 1  3  5]
 [ 7  9 11]]
Second converted Array:
[[ 2  4  6]
 [ 8 10 12]]


In [31]:
#for row wise operation,
np.concatenate((array1,array2),axis=0)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6],
       [ 8, 10, 12]])

In [32]:
#for column wise operation,
np.concatenate((array1,array2),axis=1)

array([[ 1,  3,  5,  2,  4,  6],
       [ 7,  9, 11,  8, 10, 12]])

In [34]:
#you can also concatenate array using,
print("Concatenate Arrays using vStack Method through x-axis:\n{}".format(np.vstack((array1, array2))))
#concatenate through x-axis
print("Concatenate Arrays using hStack Method through y-axis:\n{}".format(np.hstack((array1, array2))))
#concatenate through y-axis

Concatenate Arrays using vStack Method through x-axis:
[[ 1  3  5]
 [ 7  9 11]
 [ 2  4  6]
 [ 8 10 12]]
Concatenate Arrays using hStack Method through y-axis:
[[ 1  3  5  2  4  6]
 [ 7  9 11  8 10 12]]


# 3) Split

In [39]:
#split slices apart an array into multiple arrays along an axis
#np.split(array_name, [position one, position two]) specify position where array split
w=[1,2,3,4,5,6,7,8,9,10,11,12]
numpy_array=np.array(w)
np.split(numpy_array, [4,8])

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [40]:
#if you're going with two dimentional array than, you split your array like,
#np.split(array_name, [position one, position two], axis=0/1)
a=[[1,2,3,4,5,6,7,8,9], [10,11,12,13,14,15,16,17,18]]
sec_numpy_array=np.array(a)
np.split(sec_numpy_array, [3,6], axis=1)  #split array column wise

[array([[ 1,  2,  3],
        [10, 11, 12]]), array([[ 4,  5,  6],
        [13, 14, 15]]), array([[ 7,  8,  9],
        [16, 17, 18]])]

In [46]:
np.split(sec_numpy_array, [1], axis=0)  #split array row wise

[array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18]])]

# 4) Tile & Repeat

In [50]:
#these two function are the advance functions of an array
#repeat replicates each element in an array some number of times, producing a larger array
#if you pass an array of integers, each element can be repeated a different number of time
#repeats every element of an input, put the repeated numbers into a new array
#tile is the shortcut for stacking copies of an array along an axis

l=[1,2,3,4]
np_array_l=np.array(l)
print(np.repeat(np_array_l,3))  #all element repeats 3 times
print(np.tile(np_array_l,3))  #repeats the series of element 3 times

[1 1 1 2 2 2 3 3 3 4 4 4]
[1 2 3 4 1 2 3 4 1 2 3 4]
